### ISSUE TITLE
Jobs stuck on queued

### ISSUE THREAD

**Issue by WesSec** [zzzteph/sheye#1]
Hi, 

I send you an email to the admin address listed on the website. I have tried several installations of the tool but cannot seem to get it running. When adding a domain via Online tools (e.g. nmap) the tasks is not running
![image](https://user-images.githubusercontent.com/18014192/199088320-46dfcb7b-6786-4a50-8fdc-9319c429cab1.png)
![image](https://user-images.githubusercontent.com/18014192/199088382-129d33c0-c3aa-4ffa-948f-60dc2dd85bc2.png)
after running `php artisan push:queue` the status will change to queued. but the command is never run.

With some trial and error debugging I found out the handle() command in NmapCommand.php is never called (the constructor class is called)

![image](https://user-images.githubusercontent.com/18014192/199090620-ff0b2c77-8b23-42a7-9ce9-11904876e5ce.png)
and after running `push:queues`
![image](https://user-images.githubusercontent.com/18014192/199090946-51d323bb-8d65-4891-8dec-5d1e5f1e6c3b.png)
the constructor class pops up.

nmap is installed correctly and verified working
![image](https://user-images.githubusercontent.com/18014192/199091292-965b5f79-9235-419d-85ab-0adffb2c8d86.png)

I'd happily help to improve the code etc. let me know if there's a chat channel to discuss or maybe i'm just missing something here. thanks for the project!

**Comment by zzzteph** [comment]
Hey!
When the task in status `queued` it will not be executed immediately. This only means that it was added to the `jobs` table. The tasks from the `jobs` table are run through the `queue:work` jobs. 
Please, take a look at `worker.sh`. In this script, workers are running. So, you need to launch `sh worker.sh` in the background (F.E. with `screen`) and everything will be fine. In the `worker.sh` you can specify the number of workers to run.

`handler` function only executed when job from `jobs` table is picked up by `queue:work`.

**Comment by WesSec** [comment]
Makes a lot of sense, thanks for explaining, got it running rn! muchos gracias
