### ISSUE TITLE
Error when click on nuclei results

### ISSUE THREAD

**Issue by xElkomy** [zzzteph/sheye#10]
When click on nuclei results I got this error here in the screenshot:

![image](https://user-images.githubusercontent.com/46958133/214616864-501e6539-59ad-4483-aeaa-c50ce9a84a99.png)

**Comment by zzzteph** [comment]
Hey!

There is an error with the log file.

You need to go inside the container and make the storage folder writable.
For example:
```
docker exec -it 466c611adaa5 sh
chmod 777 -R storage/
```
