### ISSUE TITLE
 => ERROR [app build-go  5/10] RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

### ISSUE THREAD

**Issue by teixeira0xfffff** [zzzteph/sheye#16]
Subfinder 

 => ERROR [app build-go  5/10] RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

![image](https://github.com/zzzteph/sheye/assets/50772593/c58568b7-b885-4e81-b847-957013a19c83)

**Comment by teixeira0xfffff** [comment]
it works 

RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@v2.6.2

**Comment by teixeira0xfffff** [comment]
subfinder, httpx and dnsx with error. How i solve:

![image](https://github.com/zzzteph/sheye/assets/50772593/07c452b8-a442-4857-add5-9456224cf9f1)

**Comment by teixeira0xfffff** [comment]
my env: Linux ed912858a65c 5.15.146.1-microsoft-standard-WSL2 #1  2024 x86_64 Linux

**Comment by zzzteph** [comment]
Thanks. I believe the issue is with the go version. 
Adding exact strict versions of tools would be great idea.

**Comment by hoangtubongdem153** [comment]
can anyone help me , i have been edited the same with @teixeira0xfffff but it still not work :(( 

![image](https://github.com/zzzteph/sheye/assets/102464694/535e4888-efaf-4beb-9c8f-0d027e60c1d4)

it has the same error when i edit to lastest version (@latest / @v2.6.6) :

<img width="573" alt="image" src="https://github.com/zzzteph/sheye/assets/102464694/ec66a570-04c5-429f-b049-d3f1b7752d5f">
 
helpp me :< thankyou!

**Comment by hoangtubongdem153** [comment]
helpppp me :(

**Comment by zzzteph** [comment]
Hey @hoangtubongdem153 , sorry for taking so long to fix.

I've added strict versions to the software and now everything should be fine.
