### ISSUE TITLE
Imagines not working (incl fix)

### ISSUE THREAD

**Issue by WesSec** [zzzteph/sheye#2]
By following the Readme, the image capture of the pages is not working. To fix I did the following things

Create symlink so storage folder is found by webserver
```
cd /var/www/html/public
sudo ln -s /var/www/html/storage/app/public/ storage
```

Also the save image function is disabled by default in AnalyzeService,php, on row 82 change `UPLOAD_TO_S3 `  value to true.

Cheers

**Comment by zzzteph** [comment]
Hey, thanks!
Nice catch, will add it ASAP.

**Comment by zzzteph** [comment]
https://github.com/zzzteph/sheye/wiki/Setup#setup
